### PR TITLE
fix: remove defaultProps and propTypes

### LINKED ISSUE #1433: DefaultProps and PropTypes are causing warnings in the console
### Describe the bug

There are a lot of warnings due to the soon to be deprecated DefaultProps and PropTypes used in the design system. 

### Steps to reproduce

Run yarn build

### Expected behaviour

No warnings caused by DefaultProps and PropTypes

### Is your team blocked from moving forward by the bug?

No

### Who would you like to fix the bug?

- [ ] Myself
- [X] DesignOps

### When do you need this by?

_No response_

### Helpful resources

[Thread](https://nu.slack.com/archives/CBAFQ4X7X/p1720193394789389)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by haideralsh**
## Description
Fixes: #1433

## Changes include

- [ ] breaking change: a change that is not backwards-compatible and/or changes current functionality
- [x] fix: a non-breaking change that solves an issue
- [ ] feature: a non-breaking change that adds functionality
- [ ] chore: contains no changes affecting the library, such as documentation or test updates

## Feature checklist

- [ ] Appropriate tests have been added 
- [ ] Documentation has been updated
- [ ] Accessibility has been considered

### CODE REVIEW

File: src/List/ListItem.tsx [hunk 1]
```diff
@@ -1,19 +1,12 @@
...
-  SpaceProps &
-  ColorProps &
-  TypographyProps & {
-    className?: string;
-  };
-const ListItem: React.FC<React.PropsWithChildren<ListItemProps>> = styled.li(space, color, typography, {
+
+type Props = React.ComponentPropsWithRef<"li"> & SpaceProps & ColorProps & TypographyProps;
+
+const ListItem = styled.li<Props>(space, color, typography, {
```
Comment (haideralsh) [inline src/List/ListItem.tsx]: Missing DefaultProps

File: src/Tooltip/Tooltip.tsx [hunk 2]
```diff
@@ -26,8 +26,20 @@ export type TooltipProps = {
   children?: React.ReactNode;
 };
 
-const Tooltip: React.FC<React.PropsWithChildren<TooltipProps>> = React.forwardRef(
-  ({ className, tooltip, maxWidth, children, placement, showDelay, hideDelay, defaultOpen }, ref) => (
+const Tooltip = React.forwardRef<any, TooltipProps>(
```
Comment (haideralsh) [inline src/Tooltip/Tooltip.tsx]: Replace `any` with ref type
